### ISSUE TITLE
Whether the definition of argInt can be added？

### ISSUE THREAD

**Issue by wujilingfeng** [remiturk/libffi#14]
Acclerate depends on the definition of argInt,However, this is removed  in the latest version.

**Comment by RyanGlScott** [comment]
`argInt` was removed because it could lead to incorrect runtime results, as the size of a Haskell `Int` may not necessarily correspond to a C `int`. See [this `CHANGELOG` entry](https://github.com/remiturk/libffi/blob/dd4c54aa8f417aa436d1ac795ec647fe8fe05fd8/CHANGELOG.md?plain=1#L26-L37) for the details. The best way to adapt to this change is determine the size of the C integer type that you want and use the corresponding `argInt{8,16,32,64}` definition on the Haskell side.

I don't know how Accelerate is using `libffi`, so I'm afraid I can't offer any more specific advice than that.
